name: codedeploy
description: codedeploy
inputs:
  role-to-assume:
    required: true
  aws-region:
    required: true
  aws-ecr-registry:
    required: true
  aws-ecr-repository:
    required: true
  aws-s3-bucket:
    required: true
runs:
  using: composite
  steps:
    - id: configure-aws-credentials
      name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: ${{inputs.role-to-assume}}
        role-session-name: github-actions-role
        aws-region: ${{inputs.aws-region}}
    - id: build-appspec
      name: build appspec
      run: |
        cd codedeploy/script
        sed -i -e 's/AWS_REGION/${{ inputs.aws-region }}/g' deploy.sh
        sed -i -e 's/AWS_ECR_REGISTRY/${{ inputs.aws-ecr-registry }}/g' deploy.sh
        sed -i -e 's/AWS_ECR_REPOSITORY/${{ inputs.aws-ecr-repository }}/g' deploy.sh
      shell: bash
    - id: appspec-s3-upload
      name: appspec s3 upload
      run: |
        zip -r akari-front.zip codedeploy
        aws s3 cp akari-front.zip s3://${{inputs.aws-s3-bucket}}/
      shell: bash
    - id: codedeploy
      name: codedeploy
      run: |
        aws deploy create-deployment \
          --application-name akari-front-codedeploy-app \
          --deployment-group-name akari-front-deployment-group \
          --s3-location bucket=${{inputs.aws-s3-bucket}},key=akari-front.zip,bundleType=zip \
          --deployment-config-name akari-front-deployment-config \
          --region ${{inputs.aws-region}}
      shell: bash
