export class UrlConst {
  static readonly NINGENME_NET: string = 'https://ningenme.net'
  static readonly API_NINGENME_NET: string = 'https://api.ningenme.net'
  static readonly GITHUB: string = 'https://github.com/ningenMe'
  static readonly TWITTER: string = 'https://twitter.com/ningenMe'
  static readonly ATCODER: string = 'https://atcoder.jp/users/ningenMe'
  static readonly CODEFORCES: string = 'https://codeforces.com/profile/ningenMe'
  static readonly YUKICODER: string = 'https://yukicoder.me/users/4145'
  static readonly TOKI: string = 'https://tlx.toki.id/profiles/ningenMe'
  static readonly CSACADEMY: string = 'https://csacademy.com/user/ningenMe'
  static readonly HATENA: string = 'https://ningenme.hatenablog.com/archive'
  static readonly AMEBA: string = 'https://profile.ameba.jp/ameba/ningenme'
  static readonly QIITA: string = 'https://qiita.com/ningenMe'
  static readonly ZENN: string = 'https://zenn.dev/ningenme'
  static readonly COMPRO_LIBRARY: string = 'https://ningenme.github.io/compro-library'
  static readonly WORKS: string = 'https://indies.mangabox.me/amp/author/10633/'
  static readonly OUPC_2020: string = 'https://onlinejudge.u-aizu.ac.jp/beta/room.html#OUPC2020/info'
  static readonly YUKICODER_NINGENME: string = 'https://yukicoder.me/contests/241'
}

